package br.maua.enums;

public enum Profissao {
    ARQUEIRA,  CACADOR, CACADOR_DE_RECOMPENSAS,
    MAGO, ALQUIMISTA, FEITICEIRO, ARQUIMAGO, SACERDOTE,
    NINJA, MERCENARIO,
    GUERREIRO, ESPADACHIM, GLADIADOR,
    DEFENSOR, GUARDIAO, PALADINO, TEMPLARIO,
    TECNOMAGO,
}
